dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
cache:
  yarn: true
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
before_script:
 - chmod +x ./scripts/ci.sh
script:
  - yarn lint
  - ./scripts/ci.sh
